In [2]:
import pandas as pd
from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt
import pickle

In [3]:
import numpy as np

In [4]:
 pwd

'C:\\Users\\dell\\inuron'

In [5]:
df=pd.read_csv('advertising.csv')

In [6]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [7]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [8]:
pf=ProfileReport(df)


In [9]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
pf.to_file('test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
x=df[['TV']]
y=df[['Sales']]

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
linear=LinearRegression()

In [13]:
linear.fit(x,y)

LinearRegression()

In [14]:
linear.intercept_

array([6.97482149])

In [15]:
linear.coef_

array([[0.05546477]])

In [17]:
file='linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [16]:
linear.predict([[45]])

array([[9.47073616]])

In [19]:
l=[4,5,6,8,12,34]

In [24]:
for i in l:
    print(linear.predict([[i]]))
    

[[7.19668057]]
[[7.25214534]]
[[7.30761011]]
[[7.41853965]]
[[7.64039873]]
[[8.86062368]]


In [25]:
saved_model=pickle.load(open(file,'rb'))

In [26]:
saved_model.predict([[45]])

array([[9.47073616]])

In [17]:
linear.score(x,y)

0.8121757029987414

In [26]:
data_x=df[['TV','Radio','Newspaper']]

In [27]:
y=df.Sales

In [28]:
lm=LinearRegression()
lm.fit(data_x,y)

LinearRegression()

In [29]:
lm.intercept_

4.625124078808653

In [30]:
lm.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [31]:
lm.score(data_x,y)

0.9025912899684558

In [32]:
data1_x=df[['TV','Radio']]

In [33]:
lm1=LinearRegression()
lm1.fit(data1_x,y)
lm1.score(data1_x,y)

0.9025896186081139

In [44]:
import statsmodels.formula.api as smf
lm=smf.ols(formula='Sales~TV',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     856.2
Date:                Sat, 28 Aug 2021   Prob (F-statistic):           7.93e-74
Time:                        15:44:16   Log-Likelihood:                -448.99
No. Observations:                 200   AIC:                             902.0
Df Residuals:                     198   BIC:                             908.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.9748      0.323     21.624      0.000       6.339       7.611
TV             0.0555      0.002     29.260      0.000       0.052       0.059
==============================================================================
Omnibus:                        0.013   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.043
Skew:                          -0.018   Prob(JB):                        0.979
Kurtosis:                       2.938   Cond. No.                         338.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
lm=smf.ols(formula='Sales~TV+Radio+Newspaper',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Sat, 28 Aug 2021   Prob (F-statistic):           8.13e-99
Time:                        15:51:26   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6251      0.308     15.041      0.000       4.019       5.232
TV             0.0544      0.001     39.592      0.000       0.052       0.057
Radio          0.1070      0.008     12.604      0.000       0.090       0.124
Newspaper      0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [78]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LassoCV,ElasticNet,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
from sklearn.preprocessing import StandardScaler


In [50]:
df2=pd.read_csv('C:\\Users\\dell\\inuron\\Admission_Prediction.csv')

In [51]:
df2

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [52]:
pf2=ProfileReport(df2)

In [53]:
pf2.to_widgets()

Summarize dataset:   0%|          | 0/22 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [54]:
df2['GRE Score']=df2['GRE Score'].fillna(df2['GRE Score'].mean())

In [55]:
df2['TOEFL Score']=df2['TOEFL Score'].fillna(df2['TOEFL Score'].mean())

In [56]:
df2['University Rating']=df2['University Rating'].fillna(df2['University Rating'].mean())

## 

In [58]:
df2.describe()#no missing datas

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.103952     6.051338           1.128802    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  309.000000   103.000000           2.000000    2.500000   
50%    250.500000  316.558763   107.000000           3.000000    3.500000   
75%    375.250000  324.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [59]:
df2.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [63]:
df2.drop(columns=['Serial No.'],inplace=True)

In [64]:
df2

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [65]:
y=df2['Chance of Admit']
x=df2.drop(columns=['Chance of Admit'])

In [66]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [67]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [79]:
scaler=StandardScaler()

In [80]:
arr=scaler.fit_transform(x)

In [81]:
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [83]:
df3=pd.DataFrame(arr)

In [84]:
df3

0         1         2         3         4         5         6
0    1.842741e+00  1.788542  0.778906  1.137360  1.098944  1.776806  0.886405
1    6.708143e-01 -0.031058  0.778906  0.632315  1.098944  0.485859  0.886405
2    5.124333e-15 -0.527313 -0.107877 -0.377773  0.017306 -0.954043  0.886405
3    4.905178e-01  0.465197 -0.107877  0.127271 -1.064332  0.154847  0.886405
4   -2.306679e-01 -0.692731 -0.994659 -1.387862 -0.523513 -0.606480 -1.128152
..            ...       ...       ...       ...       ...       ...       ...
495  1.392000e+00  0.134360  1.665688  1.137360  0.558125  0.734118  0.886405
496  1.842741e+00  1.623124  1.665688  1.642404  1.639763  2.140919  0.886405
497  1.211704e+00  2.119379  1.665688  1.137360  1.639763  1.627851  0.886405
498 -4.109644e-01 -0.692731  0.778906  0.632315  1.639763 -0.242367 -1.128152
499  9.412590e-01  0.961451  0.778906  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [89]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_df=pd.DataFrame()

In [1]:
arr.shape()

NameError: name 'arr' is not defined

In [90]:
vif_df['vif']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [91]:
vif_df['feature']=x.columns

In [92]:
vif_df

vif            feature
0  4.153268          GRE Score
1  3.792866        TOEFL Score
2  2.508768  University Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

In [99]:
x_train,x_test,y_train,y_test=train_test_split(arr,y,test_size=0.25,random_state=345)

In [102]:
x_train

array([[-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [-1.67303946e+00, -1.02356739e+00,  7.78905651e-01, ...,
         1.09894429e+00, -1.46711143e+00,  8.86405260e-01],
       [-4.10964364e-01,  1.34360100e-01, -1.07876604e-01, ...,
        -5.23512832e-01, -7.68609886e-02, -1.12815215e+00],
       ...,
       [ 4.90517846e-01,  1.29228759e+00,  1.66568791e+00, ...,
         1.09894429e+00,  1.29683885e+00,  8.86405260e-01],
       [-1.67303946e+00, -1.68524024e+00,  3.93810431e-16, ...,
        -5.23512832e-01, -2.26154025e+00, -1.12815215e+00],
       [ 1.75259294e+00,  1.95396044e+00,  1.66568791e+00, ...,
         1.73062093e-02,  2.02506527e+00,  8.86405260e-01]])

In [103]:
LR=LinearRegression()

In [104]:
LR.fit(x_train,y_train)

LinearRegression()

In [106]:
pickle.dump(LR,open('admission_LR_model.pickle','wb'))

In [107]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [109]:
LR.predict()

TypeError: predict() missing 1 required positional argument: 'X'

In [110]:
test1=scaler.transform([[322.000000,110.03,3.5,2.5,8.67,1]])

ValueError: X has 6 features, but this StandardScaler is expecting 7 features as input.

In [25]:
df1=pd.read_csv('c:\\users\\dell\\downloads\\ai4i2020.csv')

In [26]:
df1.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [27]:
pf1=ProfileReport(df1)

In [28]:
pf1.to_widgets()

Summarize dataset:   0%|          | 0/27 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [30]:
df1[df1['TWF']>0].count()

UDI                        46
Product ID                 46
Type                       46
Air temperature [K]        46
Process temperature [K]    46
Rotational speed [rpm]     46
Torque [Nm]                46
Tool wear [min]            46
Machine failure            46
TWF                        46
HDF                        46
PWF                        46
OSF                        46
RNF                        46
dtype: int64

In [32]:
df1[df1['TWF']>0]

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
77      78     L47257    L                298.8                    308.9   
1087  1088     H30501    H                296.9                    307.8   
1509  1510     L48689    L                298.0                    308.5   
1682  1683     H31096    H                297.9                    307.4   
1763  1764     L48943    L                298.2                    307.6   
1996  1997     M16856    M                298.4                    308.0   
2166  2167     M17026    M                299.6                    309.2   
2244  2245     M17104    M                299.3                    308.4   
2671  2672     M17531    M                299.7                    309.3   
2864  2865     H32278    H                300.6                    309.4   
2941  2942     M17801    M                300.7                    309.6   
3529  3530     L50709    L                301.9                    310.9   
3611  3612     L50791    L                301.7                    310.9   
3695  3696     L50875    L                302.2                    311.3   
3865  3866     H33279    H                302.6                    311.5   
4034  4035     L51214    L                302.0                    310.8   
4207  4208     M19067    M                302.3                    310.9   
4385  4386     L51565    L                301.8                    309.7   
4469  4470     L51649    L                302.7                    310.5   
4646  4647     L51826    L                303.3                    311.4   
4816  4817     L51996    L                303.4                    312.0   
5141  5142     L52321    L                304.4                    313.7   
5309  5310     M20169    M                303.9                    313.2   
5401  5402     M20261    M                302.6                    312.3   
5909  5910     H35323    H                300.7                    310.2   
5999  6000     M20859    M                300.4                    310.2   
6172  6173     L53352    L                300.8                    310.6   
6256  6257     L53436    L                301.0                    310.6   
6340  6341     H35754    H                300.5                    309.9   
6419  6420     H35833    H                300.3                    309.9   
6759  6760     L53939    L                301.7                    311.0   
7087  7088     L54267    L                300.6                    310.3   
7426  7427     M22286    M                300.0                    311.4   
7510  7511     L54690    L                300.5                    311.8   
7687  7688     M22547    M                300.7                    311.7   
7849  7850     M22709    M                300.3                    311.7   
8111  8112     M22971    M                300.4                    311.8   
8199  8200     L55379    L                299.2                    310.7   
8357  8358     L55537    L                298.5                    309.5   
8609  8610     L55789    L                297.4                    308.3   
8690  8691     L55870    L                297.1                    308.5   
8846  8847     M23706    M                297.4                    308.8   
9018  9019     L56198    L                297.3                    308.1   
9174  9175     L56354    L                297.8                    308.9   
9576  9577     L56756    L                299.6                    310.7   
9758  9759     L56938    L                298.6                    309.8   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
77                      1455         41.3              208                1   
1087                    1549         35.8              206                1   
1509                    1429         37.7              220                1   
1682                    1604         36.1              225                1   
1763                    1511         31

In [31]:
df1[df1['HDF']>0].count()

UDI                        115
Product ID                 115
Type                       115
Air temperature [K]        115
Process temperature [K]    115
Rotational speed [rpm]     115
Torque [Nm]                115
Tool wear [min]            115
Machine failure            115
TWF                        115
HDF                        115
PWF                        115
OSF                        115
RNF                        115
dtype: int64